# Exercise 1 and 2: NumPy array Indexing/Slicing
 
## SIB - Intelligent Systems for Bioinformatics

Bárbara Freitas PG55693

1.1) In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file
type (use the new functions from the package)

In [5]:
import os
print(os.getcwd())

/Users/barbarafreitas/Documents/GitHub/si/tests/unit_tests


In [1]:
from si.io.csv_file import read_csv

# Loading the iris dataset

iris_dataset = read_csv('../datasets/iris/iris.csv', features=True, label=True)

1.2) Select the penultimate independent variable. What is the dimension of the resulting array?

In [5]:
# Select the penultimate independent variable

pen_variable = iris_dataset.X[:, -2]

# Determine the size of the resulting array
Number_of_dimensions = pen_variable.ndim
Shape = pen_variable.shape

print("Number of dimensions:", Number_of_dimensions)
print("Shape:", Shape)

Number of dimensions: 1
Shape: (150,)


1.3) Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?

In [10]:
# Select the last 10 samples 

last_10_samples = iris_dataset.X[-10:, :]

# Calculate the mean of each independent variable/feauture
mean_last_10 = np.mean(last_10_samples, axis=0)
print("Mean of the last 10 samples for each feature/variable:\n", mean_last_10)

Mean of the last 10 samples for each feature/variable:
 [6.45 3.03 5.33 2.17]


1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?

In [18]:
# Creating a Boolean mask to fit the condition (all features <= 6)
mask_6 = iris_dataset.X <= 6

# Identify the samples where all feautures satisfy the condition
selected_samples = np.all(mask_6, axis=1)

# Select the respective labels (samples that meet the condition
samples_meeting_condition = iris_dataset.X[selected_samples]
total_samples  = samples_meeting_condition.shape[0]

print(f"Total of samples where all independent variables are ≤ 6: {total_samples}")

Total of samples where all independent variables are ≤ 6: 89


1.5) Select all samples with a class/label different from 'Iris-setosa'. How many samples do you obtain?

In [17]:
# Creating a Boolean mask to fit the condition (amples with labels other than 'Iris-setosa')
mask_not_iris_setosa = iris_dataset.y != 'Iris-setosa'

# Select the respective labels (samples) that meet the condition
samples_not_setosa = iris_dataset.X[mask_not_iris_setosa]

print(f"Total of samples with a label other than 'Iris-setosa': {samples_not_setosa.shape[0]}")

Number of samples with a label other than 'Iris-setosa': 100


## Exercise 2: NumPy array Indexing/Slicing

Examples of how to use the methods in exercise 2

In [2]:
import numpy as np
from si.data.dataset import Dataset

In [3]:
# --- Setup with examples ---
X = np.array([[1, 2, np.nan],
              [3, 4, 5],
              [np.nan, 6, 7]])
y = np.array([10, 20, 30])

print("\n--- Example fillna ('mean') ---")
dataset = Dataset(X=np.copy(X), y=np.copy(y), label="Y")

print("Features values with missing values:\n", dataset.X)
print("Labels with missing values:", dataset.y)
print("Shape of X with missing values:", dataset.X.shape)
print("Shape of Y with missing values:", dataset.y.shape)

# Apply fillna with "mean"
dataset = dataset.fillna("mean")

print("Shape of X after fillna:", dataset.X.shape)
print("Shape of y after fillna:", dataset.y.shape)
print("Features values without missing values (filled):\n", dataset.X)
print("Labels after fillna:", dataset.y)



print("\n--- Exemplo fillna (valor 0) ---")
dataset = Dataset(X=np.copy(X), y=np.copy(y), label="Y")

print("Features values with missing values:\n", dataset.X)


# # Apply fillna with 0
dataset = dataset.fillna(0)

print("Features values without missing values (filled with 0):\n", dataset.X)


# ---------------------------------------------------
# Example remove_by_index
# ---------------------------------------------------
print("\n--- Exemplo remove_by_index (index 1) ---")
dataset = Dataset(X=np.copy(X), y=np.copy(y), label="Y")

print("Features values before removal:\n", dataset.X)
print("Labels before removal:", dataset.y)
print("Shape of X before removal:", dataset.X.shape)
print("Shape of Y before removal:", dataset.y.shape)

# Remove sample at index 1 
dataset = dataset.remove_by_index(1)

print("Shape of X after removal:", dataset.X.shape)
print("Shape of y after removal:", dataset.y.shape)
print("Features values after removal:\n", dataset.X)
print("Labels after removal:", dataset.y)


--- Exemplo fillna ('mean') ---
Features values with missing values:
 [[ 1.  2. nan]
 [ 3.  4.  5.]
 [nan  6.  7.]]
Labels with missing values: [10 20 30]
Shape of X with missing values: (3, 3)
Shape of Y with missing values: (3,)
Shape of X after fillna: (3, 3)
Shape of y after fillna: (3,)
Features values without missing values (filled):
 [[1. 2. 6.]
 [3. 4. 5.]
 [2. 6. 7.]]
Labels after fillna: [10 20 30]

--- Exemplo fillna (valor 0) ---
Features values with missing values:
 [[ 1.  2. nan]
 [ 3.  4.  5.]
 [nan  6.  7.]]
Features values without missing values (filled with 0):
 [[1. 2. 0.]
 [3. 4. 5.]
 [0. 6. 7.]]

--- Exemplo remove_by_index (index 1) ---
Features values before removal:
 [[ 1.  2. nan]
 [ 3.  4.  5.]
 [nan  6.  7.]]
Labels before removal: [10 20 30]
Shape of X before removal: (3, 3)
Shape of Y before removal: (3,)
Shape of X after removal: (2, 3)
Shape of y after removal: (2,)
Features values after removal:
 [[ 1.  2. nan]
 [nan  6.  7.]]
Labels after removal: [10 